from __future__ import annotations

from enum import StrEnum


class CompetitionCategory(StrEnum):
    HACKATHON = "HACKATHON"
    BUSINESS_CASE = "BUSINESS_CASE"
    IDEATHON = "IDEATHON"
    INNOVATION_CHALLENGE = "INNOVATION_CHALLENGE"
    STARTUP_COMPETITION = "STARTUP_COMPETITION"
    DATATHON = "DATATHON"
    AI_COMPETITION = "AI_COMPETITION"
    CONSULTING_COMPETITION = "CONSULTING_COMPETITION"
    OTHER_COMPETITION = "OTHER_COMPETITION"
    UNKNOWN = "UNKNOWN"


class DocumentKind(StrEnum):
    EVENT_ANNOUNCEMENT = "EVENT_ANNOUNCEMENT"
    REGISTRATION_OPEN = "REGISTRATION_OPEN"
    EVENT_REMINDER = "EVENT_REMINDER"
    DEADLINE_REMINDER = "DEADLINE_REMINDER"
    RESULTS_POST = "RESULTS_POST"
    WINNER_ANNOUNCEMENT = "WINNER_ANNOUNCEMENT"
    PAST_EVENT_RECAP = "PAST_EVENT_RECAP"
    NEWS_ARTICLE = "NEWS_ARTICLE"
    DIRECTORY = "DIRECTORY"
    CONFERENCE = "CONFERENCE"
    WEBINAR = "WEBINAR"
    JOB_POSTING = "JOB_POSTING"
    COURSE = "COURSE"
    UNRELATED = "UNRELATED"
    AMBIGUOUS = "AMBIGUOUS"


class EventPhase(StrEnum):
    ANNOUNCED = "ANNOUNCED"
    UPCOMING = "UPCOMING"
    ONGOING = "ONGOING"
    PAST = "PAST"
    CANCELLED = "CANCELLED"
    POSTPONED = "POSTPONED"
    UNKNOWN = "UNKNOWN"


class RegistrationState(StrEnum):
    FORTHCOMING = "FORTHCOMING"
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    UNKNOWN = "UNKNOWN"


class LocationType(StrEnum):
    ONSITE = "ONSITE"
    HYBRID = "HYBRID"
    ONLINE = "ONLINE"
    UNKNOWN = "UNKNOWN"


class DatePrecision(StrEnum):
    DATETIME = "DATETIME"
    DATE = "DATE"
    MONTH = "MONTH"
    UNKNOWN = "UNKNOWN"


class LinkTrust(StrEnum):
    """How a scraped link may be presented in an alert."""

    CLICKABLE = "CLICKABLE"
    PLAIN = "PLAIN"
    DROP = "DROP"


class CandidateState(StrEnum):
    DISCOVERED = "DISCOVERED"
    NORMALIZED = "NORMALIZED"
    FETCHED = "FETCHED"
    FETCH_DEFERRED = "FETCH_DEFERRED"
    FETCH_FAILED = "FETCH_FAILED"
    PREFILTERED = "PREFILTERED"
    EXTRACTED = "EXTRACTED"
    AMBIGUOUS = "AMBIGUOUS"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    EVENT_CREATED = "EVENT_CREATED"
    EVENT_MATCHED = "EVENT_MATCHED"
    POSSIBLE_DUPLICATE = "POSSIBLE_DUPLICATE"
    SCORED = "SCORED"
    NOTIFICATION_PENDING = "NOTIFICATION_PENDING"
    SUPPRESSED = "SUPPRESSED"
    NOTIFIED = "NOTIFIED"


class NotificationState(StrEnum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"
    SUPPRESSED = "SUPPRESSED"


class NotificationType(StrEnum):
    NEW_EVENT = "NEW_EVENT"
    REGISTRATION_OPENED = "REGISTRATION_OPENED"
    DEADLINE_CHANGED = "DEADLINE_CHANGED"
    DEADLINE_EXTENDED = "DEADLINE_EXTENDED"
    DATES_CHANGED = "DATES_CHANGED"
    VENUE_CHANGED = "VENUE_CHANGED"
    LOCATION_CHANGED = "LOCATION_CHANGED"
    ELIGIBILITY_CHANGED = "ELIGIBILITY_CHANGED"
    PRIZE_CHANGED = "PRIZE_CHANGED"
    REGISTRATION_CLOSED = "REGISTRATION_CLOSED"
    EVENT_CANCELLED = "EVENT_CANCELLED"
    EVENT_POSTPONED = "EVENT_POSTPONED"


class FailureCode(StrEnum):
    DNS_ERROR = "DNS_ERROR"
    TIMEOUT = "TIMEOUT"
    TLS_ERROR = "TLS_ERROR"
    CONNECTION_ERROR = "CONNECTION_ERROR"
    HTTP_401 = "HTTP_401"
    HTTP_403 = "HTTP_403"
    HTTP_404 = "HTTP_404"
    HTTP_429 = "HTTP_429"
    SERVER_ERROR = "SERVER_ERROR"
    CONTENT_EMPTY = "CONTENT_EMPTY"
    FETCH_DISABLED = "FETCH_DISABLED"
    JS_REQUIRED = "JS_REQUIRED"
    BROWSER_FAILED = "BROWSER_FAILED"
    PARSING_FAILED = "PARSING_FAILED"
    LLM_FAILED = "LLM_FAILED"
    RATE_LIMITED = "RATE_LIMITED"
    IMAGE_ONLY = "IMAGE_ONLY"
    PDF_UNREADABLE = "PDF_UNREADABLE"
    UNSAFE_URL = "UNSAFE_URL"
    CONTENT_TOO_LARGE = "CONTENT_TOO_LARGE"


class RejectionCode(StrEnum):
    PAST_EVENT = "PAST_EVENT"
    RESULTS_ONLY = "RESULTS_ONLY"
    NO_COMPETITION = "NO_COMPETITION"
    REGISTRATION_CLOSED = "REGISTRATION_CLOSED"
    NOT_PHILIPPINES_ELIGIBLE = "NOT_PHILIPPINES_ELIGIBLE"
    INTERNATIONAL_ONSITE = "INTERNATIONAL_ONSITE"
    DUPLICATE = "DUPLICATE"
    POSSIBLE_DUPLICATE = "POSSIBLE_DUPLICATE"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    LOW_RELEVANCE = "LOW_RELEVANCE"
    LOW_AUTHORITY = "LOW_AUTHORITY"
    FETCH_FAILED = "FETCH_FAILED"
    SEARCH_SNIPPET_ONLY = "SEARCH_SNIPPET_ONLY"
    CONFLICTING_EVIDENCE = "CONFLICTING_EVIDENCE"
    PROFILE_INCOMPLETE = "PROFILE_INCOMPLETE"
    AMBIGUOUS = "AMBIGUOUS"
