"""initial_schema

Revision ID: b38f4a7b61d4
Revises:
Create Date: 2026-08-30 19:33:41.854416
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b38f4a7b61d4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("normalized_title", sa.Text(), nullable=False),
        sa.Column("organizer", sa.Text(), nullable=True),
        sa.Column("organizer_normalized", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("document_kind", sa.String(length=64), nullable=False),
        sa.Column("event_phase", sa.String(length=32), nullable=False),
        sa.Column("registration_state", sa.String(length=32), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("registration_url", sa.Text(), nullable=True),
        sa.Column("series_key", sa.Text(), nullable=True),
        sa.Column("edition_key", sa.String(length=128), nullable=True),
        sa.Column("edition_year", sa.Integer(), nullable=True),
        sa.Column("current_facts", sa.JSON(), nullable=False),
        sa.Column("relevance_score", sa.Integer(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("material_hash", sa.String(length=64), nullable=False),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_canonical_url"), "events", ["canonical_url"], unique=False)
    op.create_index(op.f("ix_events_category"), "events", ["category"], unique=False)
    op.create_index(op.f("ix_events_edition_key"), "events", ["edition_key"], unique=False)
    op.create_index(op.f("ix_events_edition_year"), "events", ["edition_year"], unique=False)
    op.create_index(op.f("ix_events_event_phase"), "events", ["event_phase"], unique=False)
    op.create_index(
        op.f("ix_events_normalized_title"), "events", ["normalized_title"], unique=False
    )
    op.create_index(
        op.f("ix_events_organizer_normalized"), "events", ["organizer_normalized"], unique=False
    )
    op.create_index(
        op.f("ix_events_registration_state"), "events", ["registration_state"], unique=False
    )
    op.create_index(
        op.f("ix_events_registration_url"), "events", ["registration_url"], unique=False
    )
    op.create_index(
        "ix_events_series_edition", "events", ["series_key", "edition_key"], unique=False
    )
    op.create_index(op.f("ix_events_series_key"), "events", ["series_key"], unique=False)
    op.create_table(
        "proxy_health",
        sa.Column("proxy_id", sa.String(length=64), nullable=False),
        sa.Column("successful_requests", sa.Integer(), nullable=False),
        sa.Column("failed_requests", sa.Integer(), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_success", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cooldown_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("average_latency_ms", sa.Float(), nullable=True),
        sa.Column("disabled_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("proxy_id"),
    )
    op.create_table(
        "search_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("query_group", sa.String(length=64), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_search_runs_provider"), "search_runs", ["provider"], unique=False)
    op.create_table(
        "candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("discovered_url", sa.Text(), nullable=False),
        sa.Column("normalized_url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("discovery_channel", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("query", sa.Text(), nullable=True),
        sa.Column("source_key", sa.String(length=128), nullable=True),
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("rejection_reasons", sa.JSON(), nullable=False),
        sa.Column("trace", sa.JSON(), nullable=False),
        sa.Column("retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("normalized_url"),
    )
    op.create_table(
        "event_changes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("change_type", sa.String(length=64), nullable=False),
        sa.Column("field_name", sa.String(length=64), nullable=False),
        sa.Column("before_json", sa.JSON(), nullable=False),
        sa.Column("after_json", sa.JSON(), nullable=False),
        sa.Column("notify", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_changes_change_type"), "event_changes", ["change_type"], unique=False
    )
    op.create_index(op.f("ix_event_changes_event_id"), "event_changes", ["event_id"], unique=False)
    op.create_table(
        "event_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("facts_json", sa.JSON(), nullable=False),
        sa.Column("evidence_json", sa.JSON(), nullable=False),
        sa.Column("material_hash", sa.String(length=64), nullable=False),
        sa.Column("extraction_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "version"),
    )
    op.create_index(
        op.f("ix_event_versions_event_id"), "event_versions", ["event_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("event_change_id", sa.Integer(), nullable=True),
        sa.Column("notification_type", sa.String(length=64), nullable=False),
        sa.Column("dedupe_key", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("event_version", sa.Integer(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("discord_message_id", sa.String(length=64), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_change_id"],
            ["event_changes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    op.create_index(op.f("ix_notifications_event_id"), "notifications", ["event_id"], unique=False)
    op.create_index(op.f("ix_notifications_state"), "notifications", ["state"], unique=False)
    op.create_table(
        "source_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("requested_url", sa.Text(), nullable=False),
        sa.Column("final_url", sa.Text(), nullable=True),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("fetch_method", sa.String(length=32), nullable=False),
        sa.Column("proxy_used", sa.Boolean(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("last_modified", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("search_snippet", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("attempts_json", sa.JSON(), nullable=False),
        sa.Column("extraction_version", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_snapshots_candidate_id"), "source_snapshots", ["candidate_id"], unique=False
    )
    op.create_index(
        op.f("ix_source_snapshots_content_hash"), "source_snapshots", ["content_hash"], unique=False
    )
    op.create_index(
        op.f("ix_source_snapshots_event_id"), "source_snapshots", ["event_id"], unique=False
    )
    op.create_table(
        "event_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("authority", sa.Integer(), nullable=False),
        sa.Column("is_canonical", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["source_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "snapshot_id"),
    )
    op.create_index(op.f("ix_event_sources_event_id"), "event_sources", ["event_id"], unique=False)
    op.create_index(
        op.f("ix_event_sources_snapshot_id"), "event_sources", ["snapshot_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_event_sources_snapshot_id"), table_name="event_sources")
    op.drop_index(op.f("ix_event_sources_event_id"), table_name="event_sources")
    op.drop_table("event_sources")
    op.drop_index(op.f("ix_source_snapshots_event_id"), table_name="source_snapshots")
    op.drop_index(op.f("ix_source_snapshots_content_hash"), table_name="source_snapshots")
    op.drop_index(op.f("ix_source_snapshots_candidate_id"), table_name="source_snapshots")
    op.drop_table("source_snapshots")
    op.drop_index(op.f("ix_notifications_state"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_event_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_event_versions_event_id"), table_name="event_versions")
    op.drop_table("event_versions")
    op.drop_index(op.f("ix_event_changes_event_id"), table_name="event_changes")
    op.drop_index(op.f("ix_event_changes_change_type"), table_name="event_changes")
    op.drop_table("event_changes")
    op.drop_table("candidates")
    op.drop_index(op.f("ix_search_runs_provider"), table_name="search_runs")
    op.drop_table("search_runs")
    op.drop_table("proxy_health")
    op.drop_index(op.f("ix_events_series_key"), table_name="events")
    op.drop_index("ix_events_series_edition", table_name="events")
    op.drop_index(op.f("ix_events_registration_url"), table_name="events")
    op.drop_index(op.f("ix_events_registration_state"), table_name="events")
    op.drop_index(op.f("ix_events_organizer_normalized"), table_name="events")
    op.drop_index(op.f("ix_events_normalized_title"), table_name="events")
    op.drop_index(op.f("ix_events_event_phase"), table_name="events")
    op.drop_index(op.f("ix_events_edition_year"), table_name="events")
    op.drop_index(op.f("ix_events_edition_key"), table_name="events")
    op.drop_index(op.f("ix_events_category"), table_name="events")
    op.drop_index(op.f("ix_events_canonical_url"), table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
